spring.application.name=verify-x1

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/verifyx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===============================
# CORS
# ===============================

app.cors.allowed-origins=http://localhost:5173

# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# JWT
# ===============================

app.jwt.secret=VerifyXSuperSecretKey2026ForJwtAuthentication123456789
app.jwt.expiration-ms=86400000

# ===============================
# EMAIL
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=vivekmprivate1908@gmail.com

spring.mail.password=xxjhrmsrqpktgpaq
spring.mail.from=vivekmprivate1908@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# ===============================
# MAIL DEBUG
# ===============================

spring.mail.properties.mail.debug=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG

# ===============================
# APPLICATION
# ===============================

app.name=VerifyX

# ===============================
# TWILIO
# ===============================

# twilio.account-sid=
# twilio.auth-token=
# twilio.phone-number=

# ===============================
# AWS
# ===============================

aws.region=ap-south-1
education.textract.enabled=true